/** PareFood Indonesian localization */

const id = {
  app: {
    name: 'PareFood',
    tagline: 'Pesan makan, sampai di depan pintu',
  },
  auth: {
    login: 'Masuk',
    register: 'Daftar',
    logout: 'Keluar',
    email: 'Email',
    password: 'Kata sandi',
    confirmPassword: 'Konfirmasi kata sandi',
    name: 'Nama lengkap',
    phone: 'Nomor telepon',
    forgotPassword: 'Lupa kata sandi?',
    noAccount: 'Belum punya akun?',
    hasAccount: 'Sudah punya akun?',
    registerTitle: 'Buat Akun Baru',
    loginTitle: 'Masuk ke PareFood',
  },
  common: {
    loading: 'Memuat...',
    retry: 'Coba lagi',
    cancel: 'Batal',
    save: 'Simpan',
    delete: 'Hapus',
    edit: 'Edit',
    close: 'Tutup',
    confirm: 'Konfirmasi',
    yes: 'Ya',
    no: 'Tidak',
    back: 'Kembali',
    next: 'Selanjutnya',
    search: 'Cari...',
    noResults: 'Tidak ada hasil',
    emptyState: 'Belum ada data',
    error: 'Terjadi kesalahan',
  },
  order: {
    status: {
      pending_payment: 'Menunggu Pembayaran',
      paid: 'Dibayar',
      waiting_merchant: 'Menunggu Konfirmasi Merchant',
      merchant_accepted: 'Diterima Merchant',
      preparing: 'Sedang Disiapkan',
      ready_for_pickup: 'Siap Diambil',
      driver_assigned: 'Driver Ditugaskan',
      driver_picking_up: 'Driver Menuju Merchant',
      picked_up: 'Diambil Driver',
      on_delivery: 'Sedang Diantar',
      delivered: 'Terkirim',
      completed: 'Selesai',
      cancelled: 'Dibatalkan',
    },
    createOrder: 'Buat Pesanan',
    orderDetail: 'Detail Pesanan',
    myOrders: 'Pesanan Saya',
    trackOrder: 'Lacak Pesanan',
    total: 'Total',
    subtotal: 'Subtotal',
    deliveryFee: 'Biaya Pengantaran',
    serviceFee: 'Biaya Layanan',
    discount: 'Diskon',
    tax: 'Pajak',
    grandTotal: 'Total Bayar',
    payment: 'Pembayaran',
    deliveryAddress: 'Alamat Pengantaran',
    orderNotes: 'Catatan Pesanan',
  },
  merchant: {
    title: 'Menu Merchant',
    minOrder: 'Pesan Minimum',
    open: 'Buka',
    closed: 'Tutup',
    addToCart: 'Tambah ke Keranjang',
    categories: 'Kategori',
    all: 'Semua',
  },
  delivery: {
    driverOnline: 'Driver Online',
    driverOffline: 'Driver Offline',
    acceptOrder: 'Terima Pesanan',
    rejectOrder: 'Tolak Pesanan',
    startPickup: 'Mulai Pengambilan',
    markPickedUp: 'Tandai Diambil',
    markDelivered: 'Tandai Sampai',
    proofNote: 'Bukti Serah Terima',
    navigation: 'Navigasi',
    distance: 'Jarak',
    estimatedTime: 'Estimasi Waktu',
  },
  profile: {
    title: 'Profil Saya',
    editProfile: 'Edit Profil',
    addresses: 'Alamat Saya',
    addAddress: 'Tambah Alamat',
    notificationSettings: 'Pengaturan Notifikasi',
  },
  support: {
    title: 'Bantuan',
    helpCenter: 'Pusat Bantuan',
    contactUs: 'Hubungi Kami',
    faqs: 'FAQ',
    reportIssue: 'Laporkan Masalah',
  },
} as const;

export default id;
export type Localization = typeof id;